In [235]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
from tqdm.auto import tqdm
import shutil as sh

In [236]:
df = pd.read_csv('./train.csv')
df

image_id  width  height  bbox1  bbox2  bbox3  bbox4     source
0       b6ab77fd7   1024    1024  834.0  222.0   56.0   36.0    usask_1
1       b6ab77fd7   1024    1024  226.0  548.0  130.0   58.0    usask_1
2       b6ab77fd7   1024    1024  377.0  504.0   74.0  160.0    usask_1
3       b6ab77fd7   1024    1024  834.0   95.0  109.0  107.0    usask_1
4       b6ab77fd7   1024    1024   26.0  144.0  124.0  117.0    usask_1
...           ...    ...     ...    ...    ...    ...    ...        ...
147788  5e0747034   1024    1024   64.0  619.0   84.0   95.0  arvalis_2
147789  5e0747034   1024    1024  292.0  549.0  107.0   82.0  arvalis_2
147790  5e0747034   1024    1024  134.0  228.0  141.0   71.0  arvalis_2
147791  5e0747034   1024    1024  430.0   13.0  184.0   79.0  arvalis_2
147792  5e0747034   1024    1024  875.0  740.0   94.0   61.0  arvalis_2

[147793 rows x 8 columns]

In [237]:
df = df.drop(labels = ['width'],axis = 1 )
df = df.drop(labels = ['height'],axis = 1 )
df = df.drop(labels = ['source'],axis = 1 )

In [238]:
df.head()

image_id  bbox1  bbox2  bbox3  bbox4
0  b6ab77fd7  834.0  222.0   56.0   36.0
1  b6ab77fd7  226.0  548.0  130.0   58.0
2  b6ab77fd7  377.0  504.0   74.0  160.0
3  b6ab77fd7  834.0   95.0  109.0  107.0
4  b6ab77fd7   26.0  144.0  124.0  117.0

In [276]:
dd = df.values
dd
#df는 데이터 프레임인데 .values 라는 기능을 통해 리스트형으로 변형하고 출력한 값 

array([['b6ab77fd7', 834.0, 222.0, 56.0, 36.0],
       ['b6ab77fd7', 226.0, 548.0, 130.0, 58.0],
       ['b6ab77fd7', 377.0, 504.0, 74.0, 160.0],
       ...,
       ['5e0747034', 134.0, 228.0, 141.0, 71.0],
       ['5e0747034', 430.0, 13.0, 184.0, 79.0],
       ['5e0747034', 875.0, 740.0, 94.0, 61.0]], dtype=object)

In [277]:
da = dd[:,0]
da
# dd 는 리스트형 으로 바뀐 값인데 이중에서 행 전체와 열은 index 값이 0 번째인 column 을 가져와 da에 넣어준다. 

array(['b6ab77fd7', 'b6ab77fd7', 'b6ab77fd7', ..., '5e0747034',
       '5e0747034', '5e0747034'], dtype=object)

In [278]:
dd = dd[:,1:]
dd

array([[834.0, 222.0, 56.0, 36.0],
       [226.0, 548.0, 130.0, 58.0],
       [377.0, 504.0, 74.0, 160.0],
       ...,
       [134.0, 228.0, 141.0, 71.0],
       [430.0, 13.0, 184.0, 79.0],
       [875.0, 740.0, 94.0, 61.0]], dtype=object)

In [279]:
dd = dd.astype('float')
dd = dd/1024
dd

array([[0.81445312, 0.21679688, 0.0546875 , 0.03515625],
       [0.22070312, 0.53515625, 0.12695312, 0.05664062],
       [0.36816406, 0.4921875 , 0.07226562, 0.15625   ],
       ...,
       [0.13085938, 0.22265625, 0.13769531, 0.06933594],
       [0.41992188, 0.01269531, 0.1796875 , 0.07714844],
       [0.85449219, 0.72265625, 0.09179688, 0.05957031]])

In [301]:
np.savetxt('./result.txt',dd,fmt= '%1.8f')

In [302]:
dda = np.loadtxt('./result.txt')
dda

array([[0.        , 0.81445312, 0.21679688, 0.0546875 , 0.03515625],
       [0.        , 0.22070312, 0.53515625, 0.12695312, 0.05664062],
       [0.        , 0.36816406, 0.4921875 , 0.07226562, 0.15625   ],
       ...,
       [0.        , 0.13085938, 0.22265625, 0.13769531, 0.06933594],
       [0.        , 0.41992188, 0.01269531, 0.1796875 , 0.07714844],
       [0.        , 0.85449219, 0.72265625, 0.09179688, 0.05957031]])

betha = np.zeros(3374)
betha = betha.astype('object')

be = np.unique(da)
be

be = list(be)
be

betha = list([betha])
betha

be.append(betha)

In [303]:
#eliminate 0,0 in train file
for i in range(1, len(dda)):
    if dda[i,1] == float(0):
        x = np.delete(dda, (i), axis=0)

In [304]:
x

array([[0.        , 0.81445312, 0.21679688, 0.0546875 , 0.03515625],
       [0.        , 0.22070312, 0.53515625, 0.12695312, 0.05664062],
       [0.        , 0.36816406, 0.4921875 , 0.07226562, 0.15625   ],
       ...,
       [0.        , 0.13085938, 0.22265625, 0.13769531, 0.06933594],
       [0.        , 0.41992188, 0.01269531, 0.1796875 , 0.07714844],
       [0.        , 0.85449219, 0.72265625, 0.09179688, 0.05957031]])

In [306]:
np.savetxt('x.txt',x, fmt='%i %1.8f %1.8f %1.8f %1.8f')

np.savetxt('dddd.txt',bb,fmt='%.18s')

np.savetxt('betha.txt',betha,fmt='%.18s')

modelpath="./train/{alpha:09s}.txt"

for i in range(1,len(dd)):
    alpha = da[i]
    print(da[i])

In [307]:
A = []

for i in range(1,len(x)):
    alpha = da[i]
    if da[i] == da[i+1]:
        A.append(x[i])
        print('match')
    else:
        A.append(x[i])
#         np.savetxt('.txt',A,fmt='%.18s')
        np.savetxt('./txt/{0}.txt'.format(alpha),A,fmt='%i %1.8f %1.8f %1.8f %1.8f')
        A = []
        print('save')

match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
save
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
save
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
save
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
match
save
match
ma